# Generated by Django 4.1.3 on 2022-11-06 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='likes',
            field=models.BigIntegerField(default=0),
        ),
    ]
